name: first_workflow

on:
  push:
    branches: [ "main" ]

jobs:
  # =========================
  # CI JOB: BUILD + TEST + SONAR
  # =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install SonarScanner for .NET
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # ---- SONAR BEGIN ----
      - name: SonarCloud - Begin analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"krishna-puppala13_bmi-krishna" \
            /o:"krishna-puppala13" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
            /d:sonar.coverage.exclusions="**/Program.cs,**/Startup.cs,**/Pages/**/*.cs,**/Pages/**/*.cshtml"

      # ---- SONAR BEGIN ----

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test with coverage
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutput=TestResults/coverage/coverage /p:CoverletOutputFormat=opencover

      # ---- SONAR END ----
      - name: SonarCloud - End analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
      # ---- SONAR END ----
  deploy:
    needs: build        # only runs if build job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish app
        run: dotnet publish ./bmi2021/bmi2025.csproj -c Release -o ./publish
        # TODO: replace PATH/TO/YOURWEBPROJECT.csproj with your real web project path
        # e.g.: ./BMICalculator/BMICalculator.csproj

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bmi-krish'
          publish-profile: ${{ secrets.AZURE_WEBAPP }}
          package: ./publish